# Generated by Django 6.0.3 on 2026-04-15 15:26

import photo_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_web', '0002_photo_comment_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original_image',
            field=models.ImageField(upload_to=photo_web.models.photo_original_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='previous_image',
            field=models.ImageField(blank=True, null=True, upload_to=photo_web.models.photo_previous_path),
        ),
    ]
